# Identificador do projeto no SonarQube
sonar.projectKey=cimatec
sonar.projectName=Cimatec-Users

# Quais fontes analisar
sonar.sources=.

# Hostname e porta do serviço SonarQube no GitHub Actions
sonar.host.url=http://sonarqube:9000
