name: SAST com SonarCloud (CLI)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Install SonarScanner CLI
        run: |
          curl -sSLo sonar-scanner-cli.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip
          echo "${{ github.workspace }}/sonar-scanner-4.7.0-2747-linux/bin" >> $GITHUB_PATH

      - name: Create sonar-project.properties
        run: |
          cat <<EOF > sonar-project.properties
          sonar.projectKey=lucasreinaldo-bash_edu-api
          sonar.organization=lucasreinaldo-bash
          sonar.host.url=https://sonarcloud.io
          sonar.sources=.
          EOF

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.login=${SONAR_TOKEN} \
            -Djava.net.preferIPv4Stack=true
